import { Employee, Task, TaskPriority, TaskType, Product } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_0',
    name: 'Arshpreet Singh',
    email: 'arshpreet@neurowork.ai',
    password: 'admin', 
    role: 'Founder & CEO',
    accessLevel: 'ceo',
    workloadScore: 98, // Real value for calculations
    skills: ['Leadership', 'Vision', 'AI Strategy', 'Full Stack', 'Everything Everywhere All At Once'],
    status: 'BRO IS ON X-GAMES MODE 🔥',
    avatar: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=200&auto=format&fit=crop', // CEO Cat
    bio: 'Founder of NeuroWork. Passionate about leveraging Artificial Intelligence to solve complex organizational inefficiencies. Leading the vision for a fairer, more productive future of work.',
    resumeLink: '{Suppose to be a link here!}',
    portfolioLink: '{Suppose to be a link here!}',
    joinedDate: new Date('2023-01-15')
  },
  {
    id: 'emp_1',
    name: 'Sarah Chen',
    email: 'sarah@neurowork.ai',
    password: 'password123',
    role: 'Senior Developer',
    accessLevel: 'employee',
    workloadScore: 92,
    skills: ['React', 'Node.js', 'Architecture'],
    status: 'OVERLOADED',
    avatar: 'https://picsum.photos/seed/sarah/200',
    bio: 'Senior Full Stack engineer with 7 years of experience in distributed systems. Currently leading the backend migration.',
    resumeLink: '{Suppose to be a link here!}',
    portfolioLink: '{Suppose to be a link here!}',
    joinedDate: new Date('2023-03-10')
  },
  {
    id: 'emp_2',
    name: 'Mike Ross',
    email: 'mike@neurowork.ai',
    password: 'password123',
    role: 'Junior Designer',
    accessLevel: 'employee',
    workloadScore: 30,
    skills: ['Figma', 'CSS', 'Prototyping'],
    status: 'UNDERUTILIZED',
    avatar: 'https://picsum.photos/seed/mike/200',
    bio: 'Creative designer with a knack for UI/UX. Passionate about accessibility and clean design systems.',
    resumeLink: '{Suppose to be a link here!}',
    portfolioLink: '{Suppose to be a link here!}',
    joinedDate: new Date('2024-01-05')
  },
  {
    id: 'emp_3',
    name: 'Jessica Pearson',
    email: 'jessica@neurowork.ai',
    password: 'password123',
    role: 'Product Manager',
    accessLevel: 'manager',
    workloadScore: 65,
    skills: ['Strategy', 'Communication', 'Agile'],
    status: 'OPTIMAL',
    avatar: 'https://picsum.photos/seed/jessica/200',
    bio: 'Product leader focused on data-driven decision making. Bridging the gap between engineering and business goals.',
    resumeLink: '{Suppose to be a link here!}',
    portfolioLink: '{Suppose to be a link here!}',
    joinedDate: new Date('2023-02-20')
  },
  {
    id: 'emp_4',
    name: 'Louis Litt',
    email: 'louis@neurowork.ai',
    password: 'password123',
    role: 'QA Engineer',
    accessLevel: 'employee',
    workloadScore: 45,
    skills: ['Testing', 'Automation', 'Java'],
    status: 'OPTIMAL',
    avatar: 'https://picsum.photos/seed/louis/200',
    bio: 'Detail-oriented QA engineer who loves breaking things so users don\'t have to. Expert in Selenium and Jest.',
    resumeLink: '{Suppose to be a link here!}',
    portfolioLink: '{Suppose to be a link here!}',
    joinedDate: new Date('2023-06-15')
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't_1',
    title: 'Q4 Financial Report',
    description: 'Compile the quarterly earnings and project future runway.',
    longDescription: 'We need a deep dive into Q4 earnings, separating Recurring Revenue from One-time fees. Please also include a projection for Q1 runway based on current burn rate.',
    type: TaskType.MANDATORY,
    priority: TaskPriority.CRITICAL,
    estimatedHours: 12,
    assignedToId: 'emp_1',
    requiredSkills: ['Strategy'],
    status: 'IN_PROGRESS',
    progress: 45,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48), // 2 days ago
    notes: ['Initial data gathered from Stripe.', 'Waiting for expense reports from Marketing.'],
    files: ['Q4_Raw_Data.csv', 'Q3_Comparison.pdf'],
    isGroupTask: false,
  },
  {
    id: 't_2',
    title: 'Fix Login Bug',
    description: 'Users report timeout on auth service.',
    longDescription: 'The authentication service times out after 30 seconds for users in the EU region. Suspect latency in the DB replica.',
    type: TaskType.MANDATORY,
    priority: TaskPriority.HIGH,
    estimatedHours: 4,
    assignedToId: 'emp_1',
    requiredSkills: ['Node.js'],
    status: 'PENDING',
    progress: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    notes: [],
    files: ['server_logs_error.txt'],
    isGroupTask: false,
  },
  {
    id: 't_3',
    title: 'Update Landing Page',
    description: 'Refresh hero image and copy.',
    longDescription: 'The current hero image is outdated. Use the new assets from the design team drive. Update the H1 copy to "AI for the Future of Work".',
    type: TaskType.OPEN,
    priority: TaskPriority.MEDIUM,
    estimatedHours: 6,
    assignedToId: null,
    requiredSkills: ['Figma', 'CSS'],
    status: 'PENDING',
    progress: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    notes: [],
    files: ['new_hero_v2.png'],
    isGroupTask: false,
  },
  {
    id: 't_4',
    title: 'Write Unit Tests',
    description: 'Coverage for the new payment module.',
    longDescription: 'The payment module currently has 20% coverage. We need to reach at least 85% before the next release cycle.',
    type: TaskType.OPEN,
    priority: TaskPriority.LOW,
    estimatedHours: 8,
    assignedToId: null,
    requiredSkills: ['Testing', 'Java'],
    status: 'PENDING',
    progress: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    notes: [],
    files: [],
    isGroupTask: false,
  },
  {
    id: 't_5',
    title: 'Client Meeting Prep',
    description: 'Prepare slides for the Monday sync.',
    longDescription: 'Focus on the "Project Alpha" milestones. Need to show progress on the API integration.',
    type: TaskType.MANDATORY,
    priority: TaskPriority.HIGH,
    estimatedHours: 3,
    assignedToId: 'emp_3',
    requiredSkills: ['Communication'],
    status: 'IN_PROGRESS',
    progress: 80,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
    notes: ['Slides draft created.', 'Need review from Sarah.'],
    files: ['Slide_Deck_Draft.pptx'],
    isGroupTask: false,
  },
  // Group Tasks
  {
    id: 't_6',
    title: 'System Migration Alpha',
    description: 'Migrate the legacy database to the new cloud infrastructure.',
    longDescription: 'This is a critical infrastructure project. We need a team to handle data validation, schema migration, and downtime management.',
    type: TaskType.MANDATORY,
    priority: TaskPriority.CRITICAL,
    estimatedHours: 40,
    assignedToId: null,
    requiredSkills: ['Architecture', 'Node.js', 'Testing'],
    status: 'IN_PROGRESS',
    progress: 25,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    notes: ['Kickoff meeting completed.'],
    files: ['Migration_Plan_v1.pdf'],
    isGroupTask: true,
    requiredPeople: 3,
    groupAssigneeIds: ['emp_1', 'emp_4'],
  },
  {
    id: 't_7',
    title: 'Hackathon: AI Feature',
    description: 'Build a prototype for the new generative AI text editor.',
    longDescription: 'Open voluntary project for anyone interested in LLMs. Goal is to have a working demo by Friday.',
    type: TaskType.OPEN,
    priority: TaskPriority.MEDIUM,
    estimatedHours: 20,
    assignedToId: null,
    requiredSkills: ['React', 'Design', 'Strategy'],
    status: 'PENDING',
    progress: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    notes: [],
    files: [],
    isGroupTask: true,
    requiredPeople: 4,
    groupAssigneeIds: ['emp_2'],
  }
];

export const INITIAL_PRODUCTS: Product[] = [
    {
        id: 'p_1',
        name: 'NeuroFlow CRM',
        tagline: 'AI-driven Customer Relationship Management',
        description: 'NeuroFlow CRM uses predictive analytics to help sales teams identify high-value leads. It integrates seamlessly with existing email providers and offers real-time sentiment analysis during client calls.',
        status: 'Live',
        logoColor: 'from-blue-500 to-indigo-600',
        history: [
            { month: 'Jun', traffic: 12500, profit: 45000, serverCost: 12000, inputCost: 25000 },
            { month: 'Jul', traffic: 13200, profit: 48000, serverCost: 12500, inputCost: 24000 },
            { month: 'Aug', traffic: 14800, profit: 55000, serverCost: 13000, inputCost: 26000 },
            { month: 'Sep', traffic: 16000, profit: 62000, serverCost: 14500, inputCost: 28000 },
            { month: 'Oct', traffic: 15500, profit: 58000, serverCost: 14000, inputCost: 25000 },
            { month: 'Nov', traffic: 18500, profit: 75000, serverCost: 16000, inputCost: 30000 },
        ],
        topCustomers: [
            { name: 'TechGlobal Inc', type: 'Company', revenueContribution: 120000 },
            { name: 'City High School District', type: 'School', revenueContribution: 45000 },
            { name: 'GreenEarth NGO', type: 'Organization', revenueContribution: 22000 },
        ],
        devComments: [
            { id: 'c1', author: 'Sarah Chen', text: 'API response time improved by 15% after caching update.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2) },
            { id: 'c2', author: 'Mike Ross', text: 'New UI component library pushed to staging.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5) },
        ],
        serverLogs: [
            { id: 'l1', type: 'MAINTENANCE', description: 'Database migration v2.4', date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10), durationMinutes: 45 },
            { id: 'l2', type: 'OUTAGE', description: 'Redis failure in US-East', date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5), durationMinutes: 12 },
        ],
        bugReports: [
            { id: 'b1', severity: 'HIGH', title: 'Login Timeout', description: 'Users in EU experiencing timeouts.', reportedBy: 'Customer Support', status: 'OPEN', date: new Date(Date.now() - 1000 * 60 * 60 * 2) },
            { id: 'b2', severity: 'LOW', title: 'Typo in Dashboard', description: 'Dashboard says "Analytcs" instead of "Analytics".', reportedBy: 'Mike Ross', status: 'RESOLVED', date: new Date(Date.now() - 1000 * 60 * 60 * 48) },
        ]
    },
    {
        id: 'p_2',
        name: 'SecureAuth Guard',
        tagline: 'Enterprise-grade Biometric Security',
        description: 'A multi-factor authentication layer that uses behavioral biometrics to detect account takeovers. Designed for financial institutions and healthcare providers.',
        status: 'Live',
        logoColor: 'from-emerald-500 to-teal-600',
        history: [
            { month: 'Jun', traffic: 45000, profit: 95000, serverCost: 35000, inputCost: 40000 },
            { month: 'Jul', traffic: 46000, profit: 98000, serverCost: 36000, inputCost: 41000 },
            { month: 'Aug', traffic: 48000, profit: 105000, serverCost: 38000, inputCost: 42000 },
            { month: 'Sep', traffic: 52000, profit: 115000, serverCost: 42000, inputCost: 45000 },
            { month: 'Oct', traffic: 60000, profit: 140000, serverCost: 50000, inputCost: 55000 },
            { month: 'Nov', traffic: 65000, profit: 155000, serverCost: 55000, inputCost: 60000 },
        ],
        topCustomers: [
            { name: 'National Bank', type: 'Company', revenueContribution: 250000 },
            { name: 'HealthFirst Hospitals', type: 'Organization', revenueContribution: 180000 },
            { name: 'Dept of Defense', type: 'Government', revenueContribution: 500000 },
        ],
        devComments: [],
        serverLogs: [],
        bugReports: []
    },
    {
        id: 'p_3',
        name: 'CloudScale Optimizer',
        tagline: 'Serverless Infrastructure Management',
        description: 'Automatically scales cloud infrastructure based on real-time demand prediction, saving companies up to 40% on AWS and Azure bills.',
        status: 'Beta',
        logoColor: 'from-orange-500 to-red-600',
        history: [
            { month: 'Jun', traffic: 2000, profit: -15000, serverCost: 8000, inputCost: 40000 },
            { month: 'Jul', traffic: 3500, profit: -10000, serverCost: 9000, inputCost: 38000 },
            { month: 'Aug', traffic: 5000, profit: -5000, serverCost: 10000, inputCost: 35000 },
            { month: 'Sep', traffic: 8000, profit: 2000, serverCost: 12000, inputCost: 30000 },
            { month: 'Oct', traffic: 12000, profit: 15000, serverCost: 15000, inputCost: 32000 },
            { month: 'Nov', traffic: 18000, profit: 35000, serverCost: 20000, inputCost: 35000 },
        ],
        topCustomers: [
            { name: 'StreamFast Video', type: 'Company', revenueContribution: 65000 },
            { name: 'UniTech University', type: 'School', revenueContribution: 15000 },
        ],
        devComments: [
            { id: 'c3', author: 'Jessica Pearson', text: 'Beta rollout for University client scheduled next week.', timestamp: new Date() }
        ],
        serverLogs: [],
        bugReports: []
    }
];